[project]
name = "time-series-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "backtesting>=0.1.0",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "mplfinance>=0.12.10b0",
    "nseazy>=0.0.1b5",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "ta-lib>=0.6.8",
    "yfinance>=0.2.66",
]
